name: "go-redis Todos"
services:
  redis:
    container_name: redis
    image: "redis:8.0-M02"

    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  server:
    container_name: server
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
    env_file:
      - .env
      - .env.docker
    restart: always
    depends_on:
      - redis
